### ISSUE TITLE
ct.resultCheck failure

### ISSUE THREAD

**Issue by AMChalkie** [OscarBrock/gCrisprTools#8]
Hi,

Nice code, very useful. Now here is my bug:

In my case 

resultsDF <-
    ct.generateResults(
      fit,
      annotation = ann,
      RRAalphaCutoff = 0.1,
      permutations = 1000,
      scoring = "combined"
    )

produces data which fails ct.resultCheck

Error in ct.resultCheck(resultsDF) : 
  Some of the columns in the supplied result object seem to be of the wrong type. Please supply a summaryDF object generated from ct.generateResults() in the gCrisprTools package.

This fixes the problem - but should it be done within ct.generateResults?
resultsDF$geneID <- as.character(resultsDF$geneID) 

Alt / useful: 

ct.resultCheck could be more verbose in what column fails the check, rather than needing to look it up in the code here.

Thanks
/Alistair

**Comment by OscarBrock** [comment]
Thanks for this comment- you are right, the bug is actually upstream where the unprocessed annotation object is passed into the results object instead of the processed one.I'll update the code as you suggest. 

Thanks very much for catching this, and I hope you enjoy gCrisprTools!

**Comment by OscarBrock** [comment]
Hi Alistair, 

I've made the appropriate changes to the current repository, but I would recommend that you use the [Bioconductor package](http://www.bioconductor.org/packages/release/bioc/html/gCrisprTools.html) in the future, which is more actively maintained. I've pushed your suggested changes to that repository as well, but I think that they will remain in /dev until the next release.  

-R
